import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ImageCanvas from "../components/ImageCanvas";

import 'bootstrap/dist/css/bootstrap.css';

const Home: NextPage = () => {  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Plant Disease Detection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1 className={styles.title}>
            Run Plant Disease Detection
          </h1>

          <ImageCanvas width={240} height={240}/>
          <div id="result" className="mt-3">
          </div>
      </main>
    </div>
  )
}

export default Home
